apps:
  argo-cd:
    namespace: argocd
    project: default

  cilium:
    namespace: kube-system
    project: infrastructure

  gateway-api:
    namespace: kube-system
    project: infrastructure
    type: directory
    repoURL: https://github.com/kubernetes-sigs/gateway-api.git
    path: config/crd/standard
    targetRevision: v1.4.1

  metrics-server:
    namespace: kube-system
    project: infrastructure

  nvidia-device-plugin:
    namespace: nvidia-device-plugin
    project: infrastructure
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      managedNamespaceMetadata:
        labels:
          pod-security.kubernetes.io/enforce: privileged
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true

  external-secrets:
    namespace: external-secrets
    project: infrastructure
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ServerSideApply=true

  cert-manager:
    namespace: tools
    project: infrastructure

repoURL: https://github.com/Raiyajin/homelab-setup.git

defaults:
  type: helm
  project: default
  finalizer: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences: []

cluster: "https://kubernetes.default.svc"
