apiVersion: v2
name: gpu-operator
description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: nvidia-gpu-operator
    repository: https://helm.ngc.nvidia.com/nvidia
    version: 26.3.0