nvidia-gpu-operator:
  # Pre-installed on the node by Talos
  driver:
    enabled: false
  toolkit:
    enabled: false

  validator:
    driver:
      env:
        - name: DISABLE_DEV_CHAR_SYMLINK_CREATION
          value: "true"

  devicePlugin:
    enabled: true
  # Metrics exporter
  dcgmExporter:
    enabled: false
  # Automatic node labelling
  node-feature-discovery:
    enabled: true

    worker:
      config:
        core:
          # exclude 'system-os_release.VERSION_ID'
          labelWhiteList: "^(?!system-os_release.VERSION_ID$).*"