nvidia-gpu-operator:
  # Pre-installed on the node by Talos
  driver:
    enabled: false
  toolkit:
    enabled: false

  hostPaths:
    driverInstallDir: "/usr/local/glibc/usr/lib/"

  validator:
    env:
    - name: PATH
      value: "/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin"

    driver:
      env:
        - name: DISABLE_DEV_CHAR_SYMLINK_CREATION
          value: "true"
        - name: WITH_WAIT
          value: "false"

  devicePlugin:
    enabled: true
  # Metrics exporter
  dcgmExporter:
    enabled: false
  # Automatic node labelling
  node-feature-discovery:
    enabled: true

    worker:
      config:
        core:
          sources: [cpu, pci, kernel, usb, storage]