apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-homelab
spec:
  provider:
    vault:
      server: "https://openbao.internal"
      namespace: "homelab"
      caProvider:
        type: "Secret"
        namespace: "kube-system"
        name: "internal-ca"
        key: "cert"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-role"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"