global:
  namespace: "tools"

opnsense-unbound:
  apiSecret: opnsense-api

  fullnameOverride: external-dns-opnsense
  logLevel: debug
  provider:
    name: webhook
    webhook:
      image:
        repository: ghcr.io/crutonjohn/external-dns-opnsense-webhook
        tag: v1.0.0
      env:
        - name: OPNSENSE_API_SECRET
          valueFrom:
            secretKeyRef:
              name: opnsense-api
              key: api-secret
        - name: OPNSENSE_API_KEY
          valueFrom:
            secretKeyRef:
              name: opnsense-api
              key: api-key
        - name: OPNSENSE_HOST
          valueFrom:
            secretKeyRef:
              name: opnsense-api
              key: host
        - name: OPNSENSE_SKIP_TLS_VERIFY
          value: "false"
        - name: LOG_LEVEL
          value: debug

      extraVolumeMounts:
        - name: ca-certs-volume
          mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: cert
          readOnly: true

      livenessProbe:
        httpGet:
          path: /healthz
          port: http-webhook
        initialDelaySeconds: 10
        timeoutSeconds: 5

      readinessProbe:
        httpGet:
          path: /readyz
          port: http-webhook
        initialDelaySeconds: 10
        timeoutSeconds: 5

  policy: sync
  sources:
    - gateway-httproute
    - gateway-grpcroute
    
  registry: noop
  domainFilters: ["homelab.internal"]
  extraVolumes:
    - name: ca-certs-volume
      secret:
        secretName: internal-ca

ovh:
  apiSecret: ovh-api

  provider: "ovh"

  policy: sync
  sources:
    - gateway-httproute
    - gateway-grpcroute

  env:
    - name: EXTERNAL_DNS_DOMAIN_FILTER
      valueFrom:
       secretKeyRef:
         name: ovh-api
         key: dns-zone

    - name: EXTERNAL_DNS_DEFAULT_TARGETS
      valueFrom:
       secretKeyRef:
         name: ovh-api
         key: target-ip

    - name: OVH_APPLICATION_KEY
      valueFrom:
       secretKeyRef:
         name: ovh-api
         key: api-key

    - name: OVH_APPLICATION_SECRET
      valueFrom:
       secretKeyRef:
         name: ovh-api
         key: api-secret

    - name: OVH_CONSUMER_KEY
      valueFrom:
       secretKeyRef:
         name: ovh-api
         key: consumer-key
  
  extraArgs:
    - --force-default-targets