{{- range $name, $config := .Values.loadBalancers }}
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: {{ $name }}
spec:
  blocks:
    {{- toYaml $config.blocks | nindent 4 }}
---
{{- end }}