# Default values: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml
global:
  domain: argocd.platform.internal


repoURL: https://github.com/Raiyajin/homelab-setup.git

projects:
  infrastructure:
    namespace: '*'
  apps:
    namespace: '!kube-system'

argo-cd:
  server:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi

  controller:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

  redis:
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi

  dex:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi

  repoServer:
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 1Gi
