# Default values: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml
global:
  domain: argocd.homelab.internal


repoURL: https://github.com/Raiyajin/homelab-setup.git

repositories:
  - name: ghcr-charts
    type: oci
    url: oci://ghcr.io/raiyajin/charts
    project: apps
    authType: pat
    vaultPath: "kubernetes/talos-cluster/argo-cd/github/pat/homelab-ghcr-argocd"
    secret-type: repo-creds

  - name: argo-apps
    type: git
    project: apps
    url: https://github.com/Raiyajin/homelab-argo-apps.git
    authType: githubApp
    vaultPath: "kubernetes/talos-cluster/argo-cd/github/github-apps/homelab-infra-argocd"
    secret-type: repository

projects:
  infrastructure:
    namespace: '*'
    sourceRepos:
      - https://github.com/kubernetes-sigs/gateway-api.git
  apps:
    namespace: '!kube-system'
    sourceRepos:
      - https://github.com/Raiyajin/homelab-argo-apps.git
      - ghcr.io/raiyajin/charts

argo-cd:

  configs:
    params:
      server.insecure: true

  server:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi

  controller:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

  redis:
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi

  dex:
    enabled: false
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi

  repoServer:
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 1Gi
