apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ index .Values "opnsense-unbound" "apiSecret" }}
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: openbao-homelab
    kind: ClusterSecretStore
  target:
    name: {{ index .Values "opnsense-unbound" "apiSecret" }}
  data:
  - secretKey: api-key
    remoteRef:
      key: kubernetes/talos-cluster/external-dns/opnsense/api-credentials
      property: api-key
  - secretKey: api-secret
    remoteRef:
      key: kubernetes/talos-cluster/external-dns/opnsense/api-credentials
      property: api-secret
  - secretKey: host
    remoteRef:
      key: kubernetes/talos-cluster/external-dns/opnsense/api-credentials
      property: host
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.ovh.apiSecret }}
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: openbao-homelab
    kind: ClusterSecretStore
  target:
    name: {{ .Values.ovh.apiSecret }}
  data:
  - secretKey: api-key
    remoteRef:
      key: kubernetes/talos-cluster/external-dns/ovh/api-credentials
      property: api-key
  - secretKey: api-secret
    remoteRef:
      key: kubernetes/talos-cluster/external-dns/ovh/api-credentials
      property: api-secret
  - secretKey: consumer-key
    remoteRef:
      key: kubernetes/talos-cluster/external-dns/ovh/api-credentials
      property: consumer-key
  - secretKey: dns-zone
    remoteRef:
      key: kubernetes/talos-cluster/external-dns/ovh/api-credentials
      property: dns-zone