apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "node-metrics-scraping"
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: metrics-server
  egress:
  - toEntities:
    - cluster
    toPorts:
    - ports:
      - port: "10250"
        protocol: TCP
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: "6443"
        protocol: TCP