nvidia-device-plugin:
  gfd:
    enabled: true

  deviceDiscoveryStrategy: "nvml"
#   nfd:
#   enabled: true

#   worker:
#     config:
#       core:
#         sources: [cpu, pci, kernel, usb, storage]