nvidia-device-plugin:
  gfd:
    enabled: true

  deviceDiscoveryStrategy: "nvml"

  securityContext:
    capabilities:
      add:
        - SYS_ADMIN
#   nfd:
#   enabled: true

#   worker:
#     config:
#       core:
#         sources: [cpu, pci, kernel, usb, storage]