apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: {{ .Values.global.namespace }}
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: rayanhaouas792@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the DNS-01 challenge provider
    solvers:
      - dns01:
          webhook:
            groupName: {{ index .Values "cert-manager-webhook-ovh" "groupName" }}
            solverName: ovh
            config:
              # The OVH API endpoint for Europe
              endpoint: ovh-eu
              authenticationMethod: application
              applicationKeyRef:
                name: ovh-api
                key: application-key
              applicationSecretRef:
                name: ovh-api
                key: application-secret
              applicationConsumerKeyRef:
                name: ovh-api
                key: consumer-key