apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: openbao-homelab
  namespace: {{ .Values.global.namespace }}
spec:
  vault:
    path: pki/sign/cert-manager
    server: "https://openbao.internal"
    namespace: "homelab"
    caBundleSecretRef: 
      name: {{ index .Values.global "caSecret" }}
      key: "cert"
    auth:
      kubernetes:
        mountPath: "/v1/auth/kubernetes"
        role: "cert-manager-role"
        serviceAccountRef:
          name: "cert-manager"
