apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: openbao-homelab
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel
  data:
  - secretKey: token
    remoteRef:
      key: kubernetes/talos-cluster/cloudflare/cloudflared/tunnel
      property: token
