global:
  namespace: "tools"
  caSecret: internal-ca

cert-manager:
  crds:
    enabled: true
    keep: true

  config:
    enableGatewayAPI: true

cert-manager-webhook-ovh:
  groupName: "acme.raiyajin.homelab.internal"

  certManager:
    namespace: tools
