apiVersion: v2
name: cilium
description: eBPF-based Networking, Security, and Observability

type: application

version: 0.1.0

appVersion: "v1.19.2"

dependencies:
  - name: cilium
    repository: https://helm.cilium.io
    version: "v1.19.2"