cilium:
  ipam:
    mode: kubernetes
    operator:
      clusterPoolIPv4PodCIDRList: ["10.244.0.0/16"]

  kubeProxyReplacement: true
  k8sServiceHost: localhost
  k8sServicePort: 7445
  
  hubble:
    ui:
      enabled: true
    relay:
      enabled: true

      tls:
        enabled: true
        mtls: true
    
    tls:
      enabled: true
      auto:
        enabled: true
        method: certmanager

        certManagerIssuerRef:
          group: cert-manager.io
          kind: ClusterIssuer
          name: openbao-homelab

  securityContext:
    capabilities:
      ciliumAgent:
        - BPF
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
      cleanCiliumState: 
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
  cgroup:
    autoMount: 
      enabled: false
    hostRoot: "/sys/fs/cgroup"

  gatewayAPI:
    enabled: true
    hostNetwork:
      enabled: false

  l2announcements:
    enabled: true

loadBalancers:
  internal: 
    cidrs:
      - cidr: "10.50.0.201/32"
  # public: 
  #   cidrs:
  #     - cidr: "10.50.0.210/32"
