{{- range $name, $project := .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $name }}
  namespace: argocd
spec:
  sourceRepos:
    - {{ $.Values.repoURL }}
    {{ range $project.sourceRepos }}
    - {{ . }}
    {{- end }}
  destinations:
    - namespace: '{{ $project.namespace }}'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
{{- end }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: main
    path: app-of-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true